
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

db.ip=localhost
db.puerto=3306
db.nombre=sistemaabsol
db.usuario=root
db.password=escate/7845
